name: kivicare_flutter
description: A new Flutter application.

publish_to: 'none'

#Todo update version before making code zip     DO NOT REMOVE THIS TODO
version: 9.6.8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  intl_phone_field: ^3.2.0
  readmore: ^3.0.0

  cupertino_icons: ^1.0.8

  #Firebase Notification
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2

  firebase_remote_config: ^6.0.2
  firebase_core: ^4.1.1
  google_fonts: ^6.3.2
  moment_dart: ^5.3.0+1

  #State Management Technique
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  nb_utils: ^7.1.8
  mobile_scanner: ^7.1.2


  #API calling
  http: ^1.5.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-alpha.6

  # Images and Icons
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.10.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  flutter_slidable: ^4.0.3
  percent_indicator: ^4.2.5
  signature: ^6.3.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  # bar chart
  fl_chart: ^1.1.1

  #APP Information
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  flutter_custom_tabs: ^2.4.0
  get_storage: ^2.1.1

  # Pickers for image and file and dates
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  open_file: ^3.5.10
  syncfusion_flutter_datepicker: ^31.1.23
  lottie: ^3.3.2


  #PAYMENT
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^12.0.2

  # MAP
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  speech_to_text: ^7.3.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.4
  build_runner: ^2.9.0
  flutter_launcher_icons: ^0.10.0

  #dart run build_runner build --delete-conflicting-outputs


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/lottie/
    - images/flags/
    - images/filesFormat/
    - images/icons/ic_addToCart.png

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_square.png"